### ISSUE TITLE
Синтаксис логарифма с произвольным основанием

### ISSUE THREAD

**Issue by ccaid** [FarPlugins/Calculator#5]
Предлагаю такую коррекцию файла calcset.csr
```
--- calcset.csr.bak	Tue Feb 02 21:18:58 2021
+++ calcset.csr	Tue Feb 02 21:18:31 2021
@@ -200 +200 @@
-        <func syntax="log"    mean="_ln(op0) / _ln(op1)"/>
+        <func syntax="log"    mean="_ln(op1) / _ln(op0)"/>
```
Логичнее писать, ну, например, для десятичного логарифма:  log(10,какое-то-число), а не log(какое-то-число,10).
Полагаю, эта строка — просто недоделанная копипаста, если сравнить со строками выше (в патче не приведены).

**Comment by ctapmex** [comment]
не соглашусь. логичнее синтаксис log(x; base)  .  У каждого своя логика -)
ориентируюсь на https://www.ttmath.org/online_calculator

**Comment by ccaid** [comment]
настаивать не буду, но вопросы задам.
моя логика проста, в математической нотации последовательно пишется три элемента: символ логарифма (log), основание логарифма (подстрочным индексом), выражение под логарифмом.
запись сишной функции: log10(x) не противоречит математической нотации.
а в чем логика этого сайта?
и что дает возможность считать его эталоном?
какие еще сайты/библиотеки рассматривались?

**Comment by ctapmex** [comment]
данный сайт взял за основу, по причине того, что именно эта библиотека используется для расчета. Вероятно причина так себе, прямой связи нет. Но если в ней применяется такой синтаксис, то пусть будет одинаково.
создание функции, имя которой содержит информацию о базе логарифма, и той, что без базы - разные вещи. далее в кавычках имя функции
log10(x) -  "десятичный логарифм" от числа x
log(x, base) - "логарифм" от числа x по основанию base
log(base, x) - "логарифм" по основанию base числа x
как видно, первые две функции читаются одинаково. Вторая уже имеет другую логику. 
смею предположить, что функции принято писать в стиле  что сделать, над чем, доп параметры. И основание логарифма это доп параметры.

так же не маловажным будет поломка функции. если с round это было необходимо (функция работа совсем не так), то тут просто вкусовые пожелания по написанию
