### ISSUE TITLE
Вызов плагина из области Dialog

### ISSUE THREAD

**Issue by ccaid** [FarPlugins/Calculator#7]
Давно и безутешно хочется вызывать плагин из VisualCompare, который по паспорту является Dialog.

**Comment by ctapmex** [comment]
т.е. по сути вызов из макроса , которых пока тут нет в принципе ?
есть предложения, как должен выглядеть вызов ?

**Comment by ccaid** [comment]
не понял причем тут макрос.
начну издалека. вот в редакторе я нажимаю F11 — в меню присутствует калькулятор, я его могу вызвать. во вьюере я нажимаю F11 — там тоже есть калькулятор, и я его могу вызвать. а в диалоге, например, в плагине Visual Compare я нажимаю F11 — там есть куча плагинов, но калькулятора среди них нет.
то есть плагин при запуске не декларировал, что его можно вызывать из диалога.

**Comment by ctapmex** [comment]
хм, даже не знал , что это работает. думал только через макросы можно вызвать. ок, понял
